spring.application.name=tiny-ledger
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:mem:ledger
spring.datasource.driverClassName=org.h2.Driver
springdoc.default-produces-media-type=application/json
spring.h2.console.enabled=true